### ISSUE TITLE
Could not lunch

### ISSUE THREAD

**Issue by Whatchamazog** [sgear256/lululu#1]
### ERROR

Tried to find electron dependencies and I could find anything. I attempted the following: 

- I checked ~/bin for javascript. I could not find it.
- I tried git fetch and npm install for dependencies. I got the following error: 
`
*** -[__NSCFCalendar components:fromDate:]: date cannot be nil
I mean really, what do you think that operation is supposed to mean with a nil date?
An exception has been avoided for now.
A few of these errors are going to be reported with this complaint, then further violations will simply silently do whatever random thing results from the nil.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations ):
`

**Comment by sgear256** [comment]
have you tired not being bad sir? thank you have a nice day
